FROM tobi312/rpi-nginx

WORKDIR /var/www/html
ADD app/resources/public /var/www/html

ADD nginx.conf /etc/nginx/conf.d/nginx.conf

VOLUME /var/www/html/media
EXPOSE 9090

#CMD ["python", "-m", "SimpleHTTPServer", "9090"]
